# Site settings
title: KeyboardCowboy's Blog
description: Articles, reviews and musings by Chris Albrecht, a.k.a. KeyboardCowboy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://keyboardcowboy.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Exlusions
exclude: [config.codekit]
